### ISSUE TITLE
Design Docs To-Do List

### ISSUE THREAD

**Issue by mwmadsen67** [evieeee123/TripAide#1]
# Wiki Page Home

- [ ] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

---

# Database Schema

- [ ] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [ ] primary key
    - [ ] not null
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [ ] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [ ] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State

- [ ] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [ ] `entities`
        - [ ] `session`
        - [ ] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
    - [ ] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

**Comment by mwmadsen67** [comment]
Hi Evie, I made this issue for me to be able to track your progress on your design docs, and you have to be able to refer to this thread later if you have questions. Below I will leave some feedback on your current docs:

**MVP List:**
- looks perfect, nice job!

**Schema:**
- users looks good
- there is an issue with the reviews table, having a do_id, stay_id, and eat_id that are all not null is not going to work. In order for your reviews to work for spots, hotels, and restaurants you will need to create polymorphic references. I would be happy to work with you in figuring it out. Otherwise, you would need to make three separate reviews tables (one for each table you are reviewing).
- also I think some of the column names are too specific, rather than making a column of `review_title` you can just name it `title`
- In your cities table, what is city_do, city_stay, and city_eat?
- I dont think you need a photos table, you will use active storage to attach images

**Sample State:**
- the formatting looks good
- make sure not to have any underscores in your keys, since state is in javascript it should be camelCase
- After making changes to your schema, make sure to update this page to reflect any of those changes

**Backend Routes:**
- I'm not sure if you need a route for GET /api/users, this is either a user search or a user index, which is not necessary for trip advisor
- I dont think you will need a route for GET /api/reviews, since reviews will get loaded by associations from a spot /hotel / restaurant show page
- you are missing routes for spots, hotels, and restaurants

**Frontend Routes:**
- looks good, but you'll need frontend routes for spot/hotel/restaurant show pages, for example: `/restaurants/:restaurantId`
- you should also specify that something is a restaurant index or a restaurant show
- this is a good chance to plan where your map component will go also

**Comment by evieeee123** [comment]
Thanks, Mike. Based on your feedback, I updated my design docs, but I'm
still confused about the schema and routes. Can you help me figure out when
you have time?

Mike Madsen ***@***.***> 于2022年7月7日周四 12:14写道：
